### ISSUE TITLE
Uncaught TypeError: e is not a function at HTMLScriptElement.onload when using mapbox map provider

### ISSUE THREAD

**Issue by bhainesva** [yext/answers-search-ui#102]
Hi, I'm trying to include a map component by adding the following code to the `onload` of an otherwise working setup. 

```
const verticalMapConfig = {
    container: '.js-map',
    mapProvider: 'mapbox',
    apiKey: 'xxx'
}
this.addComponent('Map', verticalMapConfig);
```

This gives me the error
```
answers.min.js:1 Uncaught TypeError: e is not a function
    at HTMLScriptElement.onload (answers.min.js:1)
```

I think this is caused by this line calling loadJS without an argument: https://github.com/yext/answers/blob/master/src/ui/components/map/mapcomponent.js#L74

The mapbox provider doesn't check the arg is a function before calling it: https://github.com/yext/answers/blob/master/src/ui/components/map/providers/mapboxmapprovider.js#L25, but the google provider does: https://github.com/yext/answers/blob/master/src/ui/components/map/providers/googlemapprovider.js#L27

making the arg default to an empty func resolved the error for me locally: `  loadJS (onLoad=(() => {}))`

**Comment by b1lly** [comment]
Hi @bhainesva this should be resolved in our next patch.
