### ISSUE TITLE
IE11: hitting enter to search does not work when selecting autocomplete option

### ISSUE THREAD

**Issue by aginsberg** [yext/answers-search-ui#104]
Video here shows autocomplete not working properly on ie11 https://drive.google.com/file/d/1Q0fWZRMq6iB-U992Bv2C72RDSk37a5PH/view

**Comment by aginsberg** [comment]
@b1lly @Delerme Is it okay for Consulting to work on this?

**Comment by Delerme** [comment]
Is this for search bar or filter search?

**Comment by aginsberg** [comment]
This is for search bar autocomplete

**Comment by Delerme** [comment]
Seems fine to me, I'd try to apply the same fix to filter search when you find it too
