### ISSUE TITLE
Support analyticsOptions for each component 

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#117]
Currently (v0.7.4) analyticsOptions is only available for the answers.init config. Ideally we could have this for every component so we can support the following functionality

UniversalResults component config:
```
analyticsOptions: {
   searcher: 'UNIVERSAL'
}
```

FAQs vertical config:
```
verticalConfigId: {
   verticalConfigId: 'faqs'
}
```

**Comment by b1lly** [comment]
I'm not sure I understand the FAQ vertical config use case. Is that part of the UniversalResults component configuration?

Is the idea that for every component you want access to a `analyticsOptions` class that you can provide for initialization?

Is it not possible to accomplish providing verticalConfigId and the searcher `type` at the global level for your two particular use cases there?

**Comment by creotutar** [comment]
Yup, that is part of the UniversalResults component configuration. Ah! My mistake, that should be possible as well. Good to close this issue. I had forgotten the individual vertical pages initialize separately

**Comment by creotutar** [comment]
Reopening for the case of UniversalResults. Cannot set the global verticalConfigId when there are 2+ verticals shown.

**Comment by b1lly** [comment]
Supporting analytics at a component level might be a little tricky but I think it's worth supporting.

@Delerme will take a look


Example use case with potential interface:
```
ANSWERS.addComponent('UniversalResults', {
  config: {
     '<verticalConfigId>' : {
     'analyticsEvents': {
        verticalConfigId: '<verticalConfigId>'
     }
  }
}) 
```

**Comment by creotutar** [comment]
hello! in v0.7.5 I am noticing the change for UniversalResults component but I do not see any analyticsOptions showing for any config objects for a UniversalResults

e.g.
```
ANSWERS.init({
    apiKey: '01db1d1e5ebbaa7ea2e6807ad2196ab3',
    answersKey: 'yextanswersconfig',
    templateBundle: ...
    onReady: function () {
      this.addComponent('SearchBar', SearchBar('root'));
      this.addComponent('Navigation', Navigation('root'));
      this.addComponent('DirectAnswer', DirectAnswer());
      this.addComponent('UniversalResults', {
        container: '.js-answersUniversalResults',
        config: {
          faqs: {
            analyticsOptions: {
              verticalConfigId: 'faqs',
            }
          }
        },
      },
      transformData: ...,
       analyticsOptions: {
         'searcher': 'UNIVERSAL',
        }
      });
    },
    businessId: '919871',
})
```

searcher analytics options are showing but verticalConfigId options are not
