### ISSUE TITLE
Create 'Locator' Component

### ISSUE THREAD

**Issue by aginsberg** [yext/answers-search-ui#120]
Because of the frequent need for a vertical results column next to a map with corresponding map pins, it would be useful to have a 'Locator' component that will add both to the page with the standard Consulting Locator styling (somewhat similar to this http://cobalt.yextdemos.com.yextpages.net/search/ace)

**Comment by aginsberg** [comment]
@b1lly I believe you've already talked to Ben about this, just wanted to check if you have any concerns with what I've described above.

**Comment by b1lly** [comment]
There are higher order component stories in the product backlog, which includes this! Higher order components will be coming in future releases.
