### ISSUE TITLE
Filter Search Console Errors

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#126]
https://answers-js-demo.netlify.com/sites/subway/menu-solo

Type "bacon" and try clicking on the results
Console error, `"menu-solo:124 Uncaught TypeError: Cannot read property 'map' of undefined"`

Code: https://github.com/yext/answers-js-demo/blob/master/sites/subway/menu-solo.html
Config ID: 8
Business ID: 2287185

**Comment by rosiegrant** [comment]
(need this for marc's demo tuesday)

**Comment by rosiegrant** [comment]
looking into this further, I think this is related to the fact that clicking on a filter search option, or clicking enter on the filter search bar, is sporadically issuing a call to the answers API, which might be why it's attempting use "null" results.

**Comment by Delerme** [comment]
It was a race condition, main issue is that result components wouldn't always be provided an empty set of results (sometimes it would be undefined). Now results will always be present, but may be empty
