### ISSUE TITLE
Missing retrieveFacets=true 

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#130]
initial page load query is not submitting API call with retrieveFacets=true 

If I do a query with the search box, it does. 

https://answers-js-demo.netlify.com/sites/subway/jobs-solo?query=jobs

https://liveapi.yext.com/v2/accounts/me/answers/vertical/query?v=20190101&api_key=60cfa61574d4e06a7c490233e9a491fb&input=jobs&answersKey=subway&verticalKey=jobs&retrieveFacets=true&locale=en

**Comment by Delerme** [comment]
Initialize the dynamic filters component first (place its `addComponent` call above the one for the search bar) and it'll work. 

We may need to have an interface for components to perform some action after all components have been initialized (today, they initialize and run their actions one by one, so search bar will search without facets if facets hasn't been initialized yet) to fix the underlying issue. Do you think it's worth making a story for this feature @b1lly?

**Comment by b1lly** [comment]
Yeah, I think we need to come up with a better solution for this sooner than later.

**Comment by b1lly** [comment]
We have an item in the engineering pipeline to address this issue.
