### ISSUE TITLE
Can't provide onMount to certain components

### ISSUE THREAD

**Issue by aginsberg** [yext/answers-search-ui#145]
Some components, such as 'searchcomponent.js', have an 'onMount' defined within the component. This means that the user passing in an onMount will override the one defined in the lib's file.

**Comment by aginsberg** [comment]
@Delerme Unsure if this is intentional or not, I can remove the issue if it is intentional.

**Comment by b1lly** [comment]
It's by design that this is the behavior. The onMount from the configuration is to be considered an override. Can you describe the use case that you're trying to implement? @aginsberg 

It's something we can consider changing if there's merrit.

**Comment by aginsberg** [comment]
For Providence, I want to add some eventListeners to elements in the form. i.e. on mobile, they would like the form to expand when the user is focused on the search bar, and then collapsed after the form is submitted.

That's the only use-case I've had so far

**Comment by b1lly** [comment]
If you need to override, you can override the search onMount like so:

```
.addComponent('SearchBar', {
   ...
   onMount: function() {
      this.initSearch(this._formEl);
      this.initAutoComplete(this._inputEl);
      
      if (this.autoFocus === true && this.query.length === 0) {
        DOM.query(this._container, this._inputEl).focus();
      }

      /// custom JS here
   }
})
```

Also, we can introduce some other life cycle hooks:

1. afterMount()
2. afterRender()

@Delerme thoughts here?

**Comment by Delerme** [comment]
What's the benefit of it completely overriding? Seems like it should be run after as opposed to instead.

**Comment by b1lly** [comment]
@Delerme we wanted the flexibility for developers to be able to provide both custom templates and custom javascript without it interfering with what ships out of the box. That way they can wire up their own behaviors if they didn't like ours.

They would have access to the internal component helper methods to leverage things, but the idea of advanced implementations was that we'd push all the work directly to the developer.

We didn't want custom javascript to conflict with internal javascript for a component, so the choice was to just override completely and let the developer hook up the behavior they wanted.

**Comment by aginsberg** [comment]
> If you need to override, you can override the search onMount like so:
> 
> ```
> .addComponent('SearchBar', {
>    ...
>    onMount: function() {
>       this.initSearch(this._formEl);
>       this.initAutoComplete(this._inputEl);
>       
>       if (this.autoFocus === true && this.query.length === 0) {
>         DOM.query(this._container, this._inputEl).focus();
>       }
> 
>       /// custom JS here
>    }
> })
> ```
> 
> Also, we can introduce some other life cycle hooks:
> 
> 1. afterMount()
> 2. afterRender()
> 
> @Delerme thoughts here?

I've tried doing what you outlined above for the FilterBox component (copying over the library's onMount and adding my code below it), but it seems that 'this' is undefined in this case. Is there something I'm doing wrong

**Comment by b1lly** [comment]
You want to make sure you're not using an arrow function for the `onMount` override, otherwise the context of `this` will be undefined.

This is the correct way if you want to reference the component as `this`.

```
onMount: function() {
  this.method();
}
```

I think in the future we can probably provide the component to the handler so that you can use arrow functions.

```
onMount: (component) => {
  component.method() // as apposed to 'this`
}
```

**Comment by aginsberg** [comment]
Yes, my mistake. I'm fine with providing onMounts the way you've outlined. I'll close this issue unless somebody would like it to stay open
