### ISSUE TITLE
Implicit eventOptions for Answers Analytics

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#151]
# **Context**

Back in #117, we asked for analyticsOptions for configs.

# **Ask**

We would like to have some of the explicit information that would (as of now) be passed in through analyticsOptions be added automatically to the analytics calls, similar to how `queryId` is added to every analytics call. We see this being applicable to a few of the mandatory eventOptions for Answers analytics:

* `verticalConfigId` for every vertical
* `searcher` for UNIVERSAL vs VERTICAL
* `entityId` for the entity id of any result

This would save time and leave less room for error in setting up analytics call options.

For example, instead of writing the following, we could omit the analyticsOptions for each of the vertical config options and have the library inject the `verticalConfigId` eventOption on any analytics call within that vertical. 

```
ANSWERS.init({
    apiKey: '01db1d1e5ebbaa7ea2e6807ad2196ab3',
    answersKey: 'yextanswersconfig',
    templateBundle: ...
    onReady: function () {
      this.addComponent('SearchBar', SearchBar('root'));
      this.addComponent('Navigation', Navigation('root'));
      this.addComponent('DirectAnswer', DirectAnswer());
      this.addComponent('UniversalResults', {
        container: '.js-answersUniversalResults',
        config: {
          faqs: {
            analyticsOptions: {
              verticalConfigId: 'faqs',
            }
          }
        },
      },
      transformData: ...,
       analyticsOptions: {
         'searcher': 'UNIVERSAL',
        }
      });
    },
    businessId: '919871',
})
```

**Comment by Delerme** [comment]
Unfortunately the current component lifecycle does not make this simple. They will have to be manually provided until further notice

**Comment by b1lly** [comment]
We have a separate story for analytics 2.0. I have referenced this ticket in the feature so that we don't overlook it.
