### ISSUE TITLE
Provide option for map controls

### ISSUE THREAD

**Issue by aginsberg** [yext/answers-search-ui#158]
Allow user to pass in an option to the map component to add zoom in/out control

**Comment by aginsberg** [comment]
@b1lly @Delerme Is it okay if I add this?

**Comment by aginsberg** [comment]
This is also fairly straight-forward to accomplish on the pages side, just wondering if you'd prefer it to be in the lib

**Comment by Delerme** [comment]
@b1lly

**Comment by b1lly** [comment]
Can you elaborate on what you mean by zoom in/out control? Is it just an option as 'true' or 'false' that gets passed in? If so, yes, feel free to add.

**Comment by aginsberg** [comment]
I'm referring to have '+' and '-' buttons that cause the map to zoom in and out. Currently for citizens, we are adding it like this

`onMount: function () {
      this._map.onLoaded(() => {
        this._map.init(this._container, this.getState('map'));
        this._map._map.addControl(new mapboxgl.NavigationControl());
      });
    }`

**Comment by b1lly** [comment]
@rosiegrant has a larger map component 2.0 story that could address this.
