### ISSUE TITLE
v.0.8.0 Direct Answers value disappearing

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#166]
currently: on v0.8.0, direct answers {{answer.value}} is disappearing from the direct answer UI on a click of the thumbs up or thumbs down form

{{answer.entityName}} and {{answer.fieldName}} do not disappear

expected: a click to the thumbs up/down input should keep the direct answer in the markup

**Comment by b1lly** [comment]
@creotutar I forget whether or not this resolved? Or if it still needs to be addressed?

**Comment by creotutar** [comment]
@b1lly still happening afaik, saw it on yext answers which was rebased on v0.8.1

**Comment by b1lly** [comment]
There's an item for this in the tech-ops backlog.
