### ISSUE TITLE
Answers templates minified bundle not transpiled

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#17]
### **Issue**:
Non-transpiled minified version causing ie11 console errors (Syntax error)
https://raw.githubusercontent.com/yext/answers/dist/dist/answerstemplates.compiled.min.js?token=AHXWZJF53PUAZCWNMOPC2I25CERMI

Note all the `=>` functions in the minified version

### **Environment**:
Attached to this commit
    "answers": "yext/answers#d698272c007ff08197f79cd39dee571dd3c3a533",
Importing through webpack and javascript
`import ANSWERS from 'answers/dist/answers.min.js';`

**Comment by Delerme** [comment]
Fixed on the head of the `dist` branch: https://github.com/yext/answers/tree/67ceb48f8f13ec92c3ab202640a7855efc3ed8e6
