### ISSUE TITLE
Direct Answers thumbs up image submitting thumbs down event

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#176]
context: v0.8.0

Direct answers are currently submitting Answers Analytics for THUMBS_DOWN when you click on the thumbs up image. 

Expected: Submit a THUMBS_UP event when the thumbs up image is clicked.

**Comment by benmcginnis** [comment]
This was fixed by #194 & #195 but I'm bad at github issues so I didn't use the number
