### ISSUE TITLE
Maintain scroll of tabs after refresh (on mobile)

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#185]
**Current behavior:** On mobile, if you scroll to a tab (that's initially hidden on load) and click it, the page refreshes, and you can no longer see the tab you clicked (still hidden). https://drive.google.com/file/d/15OZDYP7vW39Hf9AewZ3tAE1Je7J8neyQ/view?usp=sharing

**Desired behavior:** when you select a tab and the page refreshes, maintain the tabs "view" (IE the place to which the tab was scrolled), so you can still see said tab after the refresh. See google example: https://drive.google.com/file/d/14FzKJyHtoOvDfyK5b-uZsaXHWDIKV2jp/view?usp=sharing

Note: we should probably also deal with this on desktop (we can do as google does but I think that's an issue that can be tracked separately)

**Comment by b1lly** [comment]
@rosiegrant can you track this enhancement on jira please?
