### ISSUE TITLE
Unexpected query change on page switch

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#20]
### *Issue*
When you search on a vertical and then switch pages, search another query, then switch back to the original page, the original query will be searched

Steps to reproduce
* Type in a search, `a`, in searchbar for page A (e.g. universal search)
* Press submit
* Navigate via the navigation component to page B (e.g. loan officers vertical page)
* Type in a search, `b`, (a != b) in searchbar for page B
* Press submit
* Navigate back to page A via the navigation component
* Search will show search for query `a`, not query `b`

### *Environment*
Attached to this commit
"answers": "yext/answers#d698272c007ff08197f79cd39dee571dd3c3a533"

**Comment by b1lly** [comment]
Note:

The actual problem:

When searching on vertical, the Navigation Component doesn't update its query string within the URL's based on the search.
