### ISSUE TITLE
Direct Answer Integration - Thumbs Down is Firing a Thumbs Up Event

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#244]
when you click the "thumbs down" icon on the direct answer card, it fires THUMBS_UP event. it should fire THUMBS_DOWN

this was taken using version `v0.8.6`:
https://drive.google.com/file/d/1LXJBXzeSYqTsJ6KymiQQdfZOz1fNiM0-/view?usp=sharing

**Comment by rosiegrant** [comment]
@b1lly @Delerme could we get this fixed as a high priority bug? happy to put in jira too just let me know. thanks!

**Comment by Delerme** [comment]
@rosiegrant 
I thought this was fixed by https://github.com/yext/answers/pull/194
Is this still happening in version after 8.1?

**Comment by b1lly** [comment]
@rosiegrant I'm going to close this. Can you re-open this in the tech-ops epic on jira if there is still an issue?
