### ISSUE TITLE
"Failed to add component" Error

### ISSUE THREAD

**Issue by Mxs2019** [yext/answers-search-ui#279]
When I try to add spellcheck I get an error "Failed to add component". The error message isn't very helpful and I'm not sure what I'm doing wrong...if you comment out spellcheck it works. 

[file.zip](https://github.com/yext/answers/files/3710003/file.zip)

**Comment by b1lly** [comment]
@bwangYext can you take a closer look at this?

**Comment by bwangYext** [comment]
Need to also point template url to the dev one. Add `templateUrl: "https://assets.sitescdn.net/answers/dev/v0.9.0/answerstemplates.compiled.min.js"` in Answers.init() under experienceVersion.

**Comment by Mxs2019** [comment]
Got it. Thanks.

**Comment by b1lly** [comment]
I added a story to make the errors more clear.
