### ISSUE TITLE
Configurable Google Map Options

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#287]
On v0.9.0, we would like to have google maps options to be able to add/remove maps controls like zoom, street viewer, and also change dragging/clicking behavior

mapConfig would ideally let us provide Google Map Options:
```
        zoom: this._zoom,
        zoomControl: false,
        fullscreenControl: false,
        streetViewControl: false,
        mapTypeControl: false,
        draggable: false,
        disableDoubleClickZoom: true,
```

Ideally this would also have the ability to differentiate between universal and vertical maps for the case when zooming is allowed on the vertical page but not on the universal

**Comment by Delerme** [comment]
@b1lly

**Comment by rosiegrant** [comment]
@creotutar I think we got most of these in our spec for default vertical searchers if you'd like to take a peek: https://docs.google.com/document/d/1UcGk-nsQkNTufKvG8QwjBUmYfecj4yDl_8kTND_TcTU/edit#heading=h.5x6xptut1buz

I grouped all of the `control` together in one `showControls` attribute, have you seen cases where people ask for some controls but not all? 

I'll add `draggable` and `disableDoubleClickZoom` (i can check but are these also possible in  Mapbox?)

Still working through how this happens on universal vs. vertical but will keep you posted there!

**Comment by Delerme** [comment]
I recommend keeping a small set of options that both providers support, and then having an option like "providerOptions" that get sent to the provider directly. This allows full control over options that only one provider supports, and avoids us having to add options to our api everytime someone requests an option that gmaps or mapbox supports

**Comment by creotutar** [comment]
hi @rosiegrant havent seen any case where anyone asks for some controls but not all for answers

**Comment by rosiegrant** [comment]
updated the spec based on @Delerme 's suggestion! https://docs.google.com/document/d/1UcGk-nsQkNTufKvG8QwjBUmYfecj4yDl_8kTND_TcTU/edit#heading=h.5x6xptut1buz

**Comment by b1lly** [comment]
Closing since there is a product item tracking it.
