### ISSUE TITLE
Map not added on click of search button, only on refresh (universal)

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#288]
On v0.9.0 for Yext Answers, when you click the search button with a search query, the map component does not populate the vertical map container with a map. This is for a universal search.

On a keypress search, the map shows as expected.

There are no console errors with this behavior.

**Comment by Delerme** [comment]
Looks like it was an issue just with google maps. The map would only show for the first search, and then not for any subsequent searches regardless of method. Fixed in #294
