### ISSUE TITLE
Map height and width set in style attribute

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#289]
In v0.9.0 the width and height of the map component is set in the style attributes which overrides css styling. Ideally, this would not be the case so we could set the height and weight of the map for universal and vertical.

In universal search: we would like to set the height of the map to 232px. This can either be done by adding a map wrapper in the library to the map that is set to 232px height, or by removing the

In vertical search: We would like to set the width of the map to 50% of the map for the layout of the locations vertical pages. This can either be done by adding a layout map wrapper on our side or removing the style attribute map width. 

We cannot use the height and width map config properties because it currently applies that to both the universal and vertical maps, which have different dimensions.

**Comment by Delerme** [comment]
We actually already had plans to do this when revisiting maps based on Rose's spec. I think it's fine to remove now though. Any concerns @benmcginnis ?

**Comment by benmcginnis** [comment]
None, please remove as part of 9.0

**Comment by Delerme** [comment]
removed in #298
