### ISSUE TITLE
HTML5 Geolocation Not Appearing

### ISSUE THREAD

**Issue by Mxs2019** [yext/answers-search-ui#290]
HTML5 geolocation should be prompted if `near_me` intent is returned but this isn't working for this query. http://answers.yext.com.yextpages.net/?query=locations+near+me&beta=true

**Comment by Mxs2019** [comment]
this could be an issue with `promptForLocation` having to be set to true. This should default to true.

**Comment by Delerme** [comment]
`promptForLocation` will default to true. Sadly the geolocation API is only accessible in secure contexts (https) so if you're testing locally with a simple http server it won't work (the link above is http). That's one reason I made the js qa app, to make it easy to test features in a secure context. Let me know if you need help with that
