### ISSUE TITLE
SpellCheck should hide on loading

### ISSUE THREAD

**Issue by Mxs2019** [yext/answers-search-ui#291]
The SpellCheck component is currently visible during the loading stage. This can be tested by running a search for a query that returns spellcheck and then running a subsequent search. During the loading phase the SpellCheck component should also be hidden.

**Comment by Mxs2019** [comment]
This might be something specific to the Yext build. Locally I think this is working but here http://answers.yext.com.yextpages.net/?query=mlcean&beta=true it's not. Not sure though.

**Comment by bwangYext** [comment]
@Mxs2019 Just pushed fix to v0.9.0.
