### ISSUE TITLE
Back button requires two clicks after a spell correction

### ISSUE THREAD

**Issue by Mxs2019** [yext/answers-search-ui#306]
**Steps to Reproduce**
1. Search for something that has spellcheck (http://answers.yext.com.yextpages.net/?query=howard+lemran&beta=true)
2. Click the correction
3. Press back

It will not take you back to the previous query. 

**Expected Behavior**
If you click a correction and then click back it should take you back to the pre-corrected query.

**Comment by bwangYext** [comment]
This fix has been pushed to v0.10.1.

**Comment by vramesh1** [comment]
closing
