### ISSUE TITLE
FAQ accordion results do not expand on click

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#307]
On v0.9.1, FAQ accordion results do not expand on click

I do not get any console errors.

**Comment by b1lly** [comment]
Do you have an example? And can you please describe what browser and what steps you took to reproduce?

Additionally, if there's any sensitive information in terms of the "example" or data, please feel free to DM me it.

**Comment by Mxs2019** [comment]
Just try to click an FAq here. It doesn't work. 

http://answers.yext.com.yextpages.net/?query=How+do+I+get+a+demo%3F

**Comment by creotutar** [comment]
DM'd you the example

Browser: Version 77.0.3865.120 (Official Build) (64-bit)
Steps to reproduce: "[serve](https://www.npmjs.com/package/serve) ." of ietest.html
   - Search for FAQ
   - Click on any FAQ Accordion Result, would expect the result to expand to show answer, not seeing this behavior
