### ISSUE TITLE
IE11 polyfills

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#311]
Attached to branch `accordian`, on ie11 on a Windows 10 machine, when I click on the searchbar to search, I get 

```
Object doesn't support property or method 'closest'
navigationcomponent.js (261,5)
```

Recommending we polyfill for a few things that Consulting is currently polyfilling for. Can DM you full file if you would like

```
    this.CustomEvents();
    this.Matches();
    this.FlatMap();
    this.Closest();
    this.Prepend();
```

**Comment by creotutar** [comment]
Note: this is not a breaking console error, I can still function around the page on IE11

**Comment by rosiegrant** [comment]
@b1lly here's the IE polyfills item

@benmcginnis @creotutar could you provide the full list of polyfills

**Comment by benmcginnis** [comment]
I've sent our polyfill code via Slack.

**Comment by creotutar** [comment]
* closest
* sendBeacon

**Comment by data-enabler** [comment]
Added polyfills for `matches`, `closest`, `prepend`, and `sendBeacon` to 0.9.2.
`flatMap` is polyfilled by Babel since it's not a browser API, and we already had a `CustomEvent` polyfill.

**Comment by benmcginnis** [comment]
Would it be possible for y'all to also pull out your list of babel plugins
that you load into an easily referenceable so we can make sure we're setup
with the same transpilation experience as y'all?

**Comment by data-enabler** [comment]
Seems like it would be easy enough to move our babel config to a separate file. Currently on a time-sensitive story, but I'll see if I can find some time to do this afterwards.

@b1lly thoughts?

**Comment by b1lly** [comment]
I put a story in the backlog for that @data-enabler .

Going to close this item thats related to the polyfill of IE.
