### ISSUE TITLE
Results images larger than their container

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#312]
On windows 10 browserstack, ie11 browser, I am seeing the image is larger than the width of its container. Would suggest adding width/height 100% to the `yxt-Result-image` class.

This is also happening on Chrome Version 77.0.3865.120 (Official Build) (64-bit).

![image](https://user-images.githubusercontent.com/32468132/67094759-6f7cc080-f182-11e9-81d3-3cd1d1ab99e0.png)

**Comment by creotutar** [comment]
Note: this is not a breaking change for Consulting sites, we set the height and width by default for all images

**Comment by data-enabler** [comment]
Currently affecting answers.yext.com as well:
![Screen Shot 2019-10-22 at 7 24 40 PM](https://user-images.githubusercontent.com/1616815/67343153-700ab380-f502-11e9-97c5-14171f6a1072.png)

Looks like this is actually a [browser bug in the handling of `img` elements in flex containers](https://bugs.chromium.org/p/chromium/issues/detail?id=625560), but Firefox is the only browser that doesn't have this bug.

**Comment by b1lly** [comment]
A fix went out in the last version.
