### ISSUE TITLE
Navigation link analytics: no vertical_config_id

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#316]
Version 0.9.1
Chrome Version 77.0.3865.120 (Official Build) (64-bit).
Seeing this behavior for both BBVA and Yanswers

Getting 400 with response "Record missing required field: vertical_config_id" when I click on navigation links.

Steps to recreate
* Visit answers.yext.com
* Cmd + Click on App Directory nav link

It looks like the eventoptions are not being added to the html. Ideally, the vertical_config_id eventoption would be added automatically by the library (as navigation is given configId)

**Comment by rosiegrant** [comment]
@b1lly I have verified this is an issue, we should resolve in the next version if possible!

**Comment by Delerme** [comment]
Fixed in v0.9.2
