### ISSUE TITLE
Scroll zoom on map

### ISSUE THREAD

**Issue by aginsberg** [yext/answers-search-ui#319]
On Universal Results, it would be good to have the option to disable scroll zoom on the map. Example of how this can be done for mapbox: https://docs.mapbox.com/mapbox-gl-js/example/disable-scroll-zoom/index.html

**Comment by rosiegrant** [comment]
we gotchu

map updates: https://docs.google.com/document/d/1UcGk-nsQkNTufKvG8QwjBUmYfecj4yDl_8kTND_TcTU/edit#heading=h.5x6xptut1buz

specifically disabling scroll for mapbox is covered here: https://docs.google.com/document/d/1UcGk-nsQkNTufKvG8QwjBUmYfecj4yDl_8kTND_TcTU/edit#heading=h.ixb0q33b47ie

**Comment by b1lly** [comment]
Product has a spec for this now. Closing.
