### ISSUE TITLE
Navigation Component Tab Reordering

### ISSUE THREAD

**Issue by aginsberg** [yext/answers-search-ui#323]
There are cases when navigating to a new vertical will cause the tabs to reorder. This happens on https://answers.three.co.uk

Steps to reproduce:
1. Search for 'iphone'
2. Click 'view all' in the products results section

Video here https://drive.google.com/file/d/1aXNrqbRLZ3VLBURKQmeWZxLK4dBkzn8f/view?usp=sharing

**Comment by rosiegrant** [comment]
i've verified this is an issue (happening in chrome at a minimum). 

Note that clicking the **navigation** correctly passes the tab params, but clicking "view all" does not. 

I also went way back to the early 8s (~v0.8.2) and verified it was still happening.

**Comment by rosiegrant** [comment]
@vramesh1 I'm going to check if this is still happening in 10 and will update here -- if so would be good to fix this :)

**Comment by b1lly** [comment]
@rosiegrant Have you confirmed if this is still an issue? Can I close this?

**Comment by vramesh1** [comment]
closing.
feel free to re-open if this is still an issue.
