### ISSUE TITLE
Double clear button on Microsoft browsers

### ISSUE THREAD

**Issue by aginsberg** [yext/answers-search-ui#330]
Microsoft browsers will add a clear button to all <input> elements by default. We should probably use CSS to hide these:
https://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs

**Comment by rosiegrant** [comment]
@aginsberg confirming this was happening on IE11?

**Comment by aginsberg** [comment]
Yes, one of the clear buttons comes from the library, the other one is the default added by the browser

**Comment by Delerme** [comment]
Fixed in v0.9.2
