### ISSUE TITLE
preserve full stack trace when throwing a new AnswersComponentError

### ISSUE THREAD

**Issue by benmcginnis** [yext/answers-search-ui#338]
This line:
https://github.com/yext/answers/blob/083133b17471b4bbbed76139799e82601d999be1/src/ui/components/component.js#L233

Clobbers the underlying error & stack trace in the error that's ultimately thrown making it very difficult to diagnose underlying problems.

**Comment by vramesh1** [comment]
Backlogged into our JIRA board for future prioritization.
https://yexttest.atlassian.net/browse/WAT-647.
This story was later deleted in favor of 
https://yexttest.atlassian.net/browse/WAT-641.
Currently working on higher priority items.
Closing.
