### ISSUE TITLE
Multiple Accordion Verticals

### ISSUE THREAD

**Issue by aginsberg** [yext/answers-search-ui#348]
If multiple verticals are using the accordion template, and at least 2 of those verticals return results on the universal search page, the latter's toggles will not work. This behavior can be observed here http://af247.yext-cdn.com.yextpages.net/index.html?query=apply+for+a+loan&tabOrder=all%252Clocations%252Cfaqs%252Cproducts. I have also tested this on the OOBX and had the same results.

**Comment by data-enabler** [comment]
Is that link still good? I'm only seeing one set of Accordion Results.

**Comment by aginsberg** [comment]
It doesn't look like that site is using multiple verticals with accordions anymore.

**Comment by aginsberg** [comment]
I've set up a test here https://github.com/yext/answers-oobx-test/blob/issue348-test/ietest.html. If you query "bill", it will return results for FAQs and Links, but only the FAQ accordions work

**Comment by data-enabler** [comment]
Thanks a lot!

**Comment by data-enabler** [comment]
This will be fixed in v0.10.1
