### ISSUE TITLE
ie11 bug in 9.3

### ISSUE THREAD

**Issue by benmcginnis** [yext/answers-search-ui#360]
It looks like this line: https://github.com/yext/answers/blob/c15b5f4828535585c227b47b4936f4996889f5f2/src/ui/storage/persistentstorage.js#L62 

is un-polyfilled in IE11.

Error: `Object doesn't support property or method 'delete'`

<img width="1792" alt="Screen Shot 2019-11-13 at 12 47 13 PM" src="https://user-images.githubusercontent.com/1206953/68789875-4716a380-0614-11ea-8849-f20e181a3299.png">

Tested using the answers oobx tester.

**Comment by data-enabler** [comment]
Hmm, any particular reason we rolled our own shim instead of using an existing polyfill?
@creotutar

**Comment by benmcginnis** [comment]
At the time @b1lly was concerned about introducing polyfills that would pollute the global environment.

**Comment by benmcginnis** [comment]
Since that ship has sailed, we should probably consider just introducing the appropriate polyfill

**Comment by vramesh1** [comment]
Backlogged into our JIRA board for future prioritization.
https://yexttest.atlassian.net/browse/WAT-646.
Currently working on higher priority items.
Closing.
