### ISSUE TITLE
LocationBias Component - After Denying, Locate Link is Showing Up Again

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#364]
Spec: https://docs.google.com/document/d/1NYHebkslc1mozi2to0bHYSutbdeog65XP0-MLUYG5XA/edit#heading=h.lfwl78dagaas

**Current behavior:** 
If a User clicks “deny”, system should continue to display greyed out circle, and no “Update your location” link. On refresh, it displays the link again (and clicking it does nothing, since it's a browser setting issue).

**Expected Behavior**
If a User clicks “deny”, system should continue to display greyed out circle, and no “Update your location” link. On refresh, the link should remain hidden. Might need to do this: https://stackoverflow.com/questions/6092400/is-there-a-way-to-check-if-geolocation-has-been-declined-with-javascript

**Comment by rosiegrant** [comment]
@vramesh1 any chance we could get this into the next non-breaking cut (ideally early next week)?

**Comment by vramesh1** [comment]
@rosiegrant, the next non-breaking version we're contributing towards is 10.0.1.
can this be merged into that version?
or do we need this on 0.9.x?

**Comment by rosiegrant** [comment]
we need it on 0.9.x

**Comment by vramesh1** [comment]
Ok.
I see another issue related to LocationBiasComponent.
Does that need to be in 0.9.x as well?
What are all the issues that will need to be addressed in 0.9.x that cannot be on 0.10.x?

**Comment by rosiegrant** [comment]
yeah good q -- this is the only one that needs to be on 0.9.x 

the other issue wasn't specified in the spec, so I don't think it's reasonable to ask that it be retroactively added :)

**Comment by vramesh1** [comment]
cool, thanks.
wanted to identify candidate fixes for hot-fixing into the older versions so that we try to cut less frequently on the older versions, and focus on newer versions.
we'll get this fix into 0.9.5.

**Comment by rosiegrant** [comment]
i think we're good to close this, verified it's working!
