### ISSUE TITLE
dist-v0.9.3 and dist-v0.9.4 gitignore dist

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#366]
While trying to `npm install` on the tag dist-v0.9.3 and dist-v0.9.4, I am not getting the `dist/` directory because it is in the .gitignore. Possible to remove? This is not a problem for dist-v0.9.2, but I am looking to upgrade for the location bias component.

**Comment by vramesh1** [comment]
Will fix this today

**Comment by vramesh1** [comment]
@creotutar, I removed dist/ from .gitignore and pushed this change to tags dist-v0.9.3 and dist-v0.9.4
