### ISSUE TITLE
Navigation Component - v0.9.0 VERTICAL_TAB_NAVIGATION event 400-ing

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#378]
Pretty sure it's because we're not passing the verticalConfigId to the event 

![image](https://user-images.githubusercontent.com/22160788/69180288-08349200-0adb-11ea-9683-f8c4460a56aa.png)

**Comment by rosiegrant** [comment]
@vramesh1 we have a bunch of people on 0.9.0, so this would be a good bug to retroactively fix (otherwise we need everyone to upgrade) -- let me know your thoughts!

**Comment by vramesh1** [comment]
okay.
if it is an urgent fix that needs to be deployed on clients' current version (0.9), we can merge the fix into 0.9.x as needed.

**Comment by data-enabler** [comment]
The fix for this should already be on 0.9.2:
https://github.com/yext/answers/commit/9d84f75c3a14b1f07afe2b5c96dfa0afdc22f476
