### ISSUE TITLE
Pass sessionTrackingEnabled Param to Autocomplete Endpoint

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#419]
**Background:** In the SDK, in the `ANSWERS.init`, an implementer can set `sessionTrackingEnabled: false`

However, on our /autocomplete calls, we do not appear to be passing the `sessionTrackingEnabled` param, which means the server is still attempting to set a cookie when it's been set to `false` in the SDK. 

**Desired Behavior**: The `sessionTrackingEnabled` param should be appended to **all** requests, including autocomplete.  

No one is using this param yet, so this is not hugely urgent, but we should still fix ASAP.

**Comment by rosiegrant** [comment]
@data-enabler you had some thoughts on how to implement this, feel free to add them here

**Comment by data-enabler** [comment]
Ideally this should be done at a level where it's not possible to accidentally omit the param from Answers API requests

**Comment by tmeyer2115** [comment]
Resolved by commit #463 in v0.12.1

**Comment by rosiegrant** [comment]
just noting that I tested this on /dev/v0.12.1 and correctly, I do not see a sessionId being set when sessionTrackingEnabled: false 

![image](https://user-images.githubusercontent.com/22160788/73017695-3d68a380-3dee-11ea-8e0e-9caaf8b71255.png)


And when sessionTrackingEnabled: true, confirming i do see the sessionID

<img width="1552" alt="Screen Shot 2020-01-23 at 2 42 10 PM" src="https://user-images.githubusercontent.com/22160788/73017933-97696900-3dee-11ea-9b56-cb40ab4c3715.png">
