### ISSUE TITLE
Result Title Link Target

### ISSUE THREAD

**Issue by aginsberg** [yext/answers-search-ui#427]
In this template https://github.com/yext/answers/blob/master/src/ui/templates/results/resultsitem.hbs#L34, it looks like you should be able to set the 'target' property of the title link. It doesn't appear that the 'target' property is attached to '_config', but rather '_config._parentOpts'.

I've set up a demo here https://github.com/yext/answers-oobx-test/commit/40abc8f8239a44a0b5f9c979038b8a95268ad617

**Comment by benmcginnis** [comment]
@tmeyer2115 how would you feel about taking a peek at this?

**Comment by tmeyer2115** [comment]
Hey Ben, @oshi97 will be starting to help out with the SDK as well. If it's alright, we'll have him tackle this item once he's up and running.
