### ISSUE TITLE
Reset Css for SearchBar / GeoLocationFilter High Specificity 

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#456]
On v0.12.0

Trying to style the GeoLocationFilter search bar input with the following class selector `yxt-GeoLocationFilter-input` but the styling is overridden by the reset css `.yxt-GeoLocationFilter input[class*=yxt-]` (e.g. when trying to add a border to a search bar). This is a change that would affect all css for sites upgrading from pre v0.12.0 to v0.12.0 if they are overridden in the reset css.

We can match specificity of the reset css with `.yxt-GeoLocationFilter input[class*=yxt-]` but that's not clear or super consumer friendly. Could we have the reset css have specificity lower than the single element classes like `yxt-GeoLocationFilter-input`? Or do we suggest another way of overriding the reset css?

**Comment by tmeyer2115** [comment]
This should be resolved by #460

**Comment by creotutar** [comment]
hey @tmeyer2115 this is also happening for yxt-Results-filters

is it possible to have styling changes be reset generally in a less specific manner?

<img width="273" alt="Screen Shot 2020-01-21 at 2 34 00 PM" src="https://user-images.githubusercontent.com/32468132/72836670-175eca00-3c5b-11ea-82da-9fd52e9e7f95.png">

**Comment by tmeyer2115** [comment]
@creotutar Yep, should be possible. I can add those resets as part of a single element class's styling. Seems like we shouldn't be trying to do any global, high specificity resets like that as it causes problems for custom styling.

**Comment by tmeyer2115** [comment]
Fixed in v0.12.1.
