### ISSUE TITLE
Refreshing Page Does Not Preserve Applied Filters

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#461]
1. Conduct a search with filters (facet, date range, static filter, likely range filter too) 
2. Refresh the page 

Current behavior: The filter is not preserved in the search results. In other words, it is not applied to the live api call. The filter information is still visually displayed and is in the URL for the page, just not the liveapi request.

Expected behavior: The filter would continue to be applied. 

(https://yext.slack.com/archives/CJ5B4TYBC/p1579291359002100)

**Comment by oshi97** [comment]
Came up with a fix for Providence with @creotutar and @tmeyer2115 on Friday, I think we're planning to just add the fix to the dev branch sometime soon!

**Comment by oshi97** [comment]
This has been fixed for all filters/facets. Yay!
