### ISSUE TITLE
Static Filters Updates Do Not Seem to Pass Initial Query

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#462]
**To replicate:**
- https://answers-js-demo.netlify.com/sites/rose/employees-static-filters.html
- search for “catherine” (request: https://liveapi.yext.com/v2/accounts/me/answers/vertical/query?v=20190101&api_key=df4b24f4075800e5e9705090c54c6c13&jsLibVersion=v0.12.0&input=catherine&experienceKey=rosetest&version=STAGING&filters=%7B%7D&verticalKey=people&limit=20&offset=0&retrieveFacets=true&locale=en&sessionTrackingEnabled=true)
- under the static filters, click “roses friend” (request: https://liveapi.yext.com/v2/accounts/me/answers/vertical/query?v=20190101&api_key=df4b24f4075800e5e9705090c54c6c13&jsLibVersion=v0.12.0&input=catherine&experienceKey=rosetest&version=STAGING&filters=%7B%22c_awards%22%3A%7B%22%24eq%22%3A%22Roses%20Friend%22%7D%7D&facetFilters=%7B%22c_employeeDepartment%22%3A%5B%5D%2C%22c_interests%22%3A%5B%5D%7D&verticalKey=people&limit=20&retrieveFacets=true&locale=en&sessionTrackingEnabled=true)

**Current behavior:** Sophia starts coming back -- it appears that the static filters are losing the initial query

**Expected Behavior:** Just Catherine Dworak would return. 

Tom's note: "The query we send after applying the “roses friend” filter. the request seems correct. it has “catherine” as the input and filters has {“c_awards”:{“$eq”:“Roses Friend”}}", so potentially this is a Watson issue

**Comment by tmeyer2115** [comment]
This is actually the expected behavior. When a filter is applied, the back-end returns all entities that match that filter. The order in which they are returned, their rank, is determined by how closely they match the search text itself.
