### ISSUE TITLE
Search flashes QASubmission Component before content loads

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#466]
On v0.12.0

Submitting a search causes the QA Submission component to flash before the content is loaded, and then the component is pushed down by the content when it loads. Would expect all of the content to load at the same time.

Steps to recreate
Using an answers site with a QASubmission, Results, and SearchBar component: where QASubmission component is under the Results component
1. Type into searchbar
2. Press Enter
3. See the QA Submission box show up before results
4. QA Submission is pushed down when results show up

**Comment by tmeyer2115** [comment]
Fixed in v0.12.1
