### ISSUE TITLE
Lifecycle events called twice

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#502]
on v12,

As discussed with @tmeyer2115 

Lifecycle events onMount, onStateChange, and onUpdate (have not tested others) are called twice. For example, on the load of a page, onMount is called twice for the UniversalResults. On a search in the search bar, onUpdate is called twice for the VerticalResults. There is no way to distinguish these events through the parameters. If we want to send custom analytics events only once the results have loaded (onMount) or once a search has completed (onUpdate), this is not possible without finagling a "lock" on the window.

**Comment by creotutar** [comment]
Use case: send an analytics event on page load and on subsequent searches

* Cannot use onStateChange as this is called at least twice (I noticed four times on a refresh for a few initializations of components)
* Cannot use onUpdate as this is called at least twice (possibly more for "near me" queries)
* Cannot use onMount as this is called at least twice (a UniversalResults onMount is called and then a subsequent search triggers another UniversalResults onMount)

**Comment by rosiegrant** [comment]
@tmeyer2115 to estimate this this week. thanks tom!

**Comment by rosiegrant** [comment]
per Amani, this is an issue especially when integrating with Adobe analytics. API call seems to be pretty straightforward to adobe, just difficult to make given our lifecycle evnets.

- Citizens and Cox: Trigger an event every time a search is conducted.
- Citizens: Whenever someone clicks "submit a question", trigger an event with necessary information. 
- Vanguard and Verizon: Both use Adobe. This hasn't come up for them yet but could in the future.

@creotutar could you confirm that just making sure our lifecycle events not being called twice will handle the above issues? just want to confirm there's nothing else we're missing as tom estimated :)

**Comment by creotutar** [comment]
@rosiegrant This will handle some of the issues. However, we would need to have some onSearch lifecycle (that is not called on page load, only through searchbar searches) or onAllComponentsLoaded so we can call analytics with 100% knowledge that all the information is on the DOM. 

Use case for onSearch: only call analytics when a searchbar search is done.
Use case for onAllComponentsLoaded: an analytics call needs to be built with information from both UniversalResults and DirectAnswers

**Comment by oshi97** [comment]
Hi @creotutar,

For the on page load analytics, would it be possible for you to fire the analytics event yourself inside ANSWERS.init's onReady? I'm not sure if we want to add some onAllComponentsLoaded hook, since the sdk lets you add components whenever you want. What kind of information do you need in this analytics call?

For on search analytics, do you want this to be only when a search is run through the search bar component, or whenever a search is run for any reason (like changing the filters/sort options)?

**Comment by creotutar** [comment]
Hi @oshi97,

Q1: Sure. Not a problem currently, but I can see it being a problem in the future. So in one of our cases, we need to send ONE analytics call when UniversalResults has finished loading its results. This call needs to be built with information like # results returned and search query used. Ideally we'd be able to get this information from the SearchBar component somehow on its onMount (or maybe the UniversalResults onMount, who knows) instead of having to use the URL query and some DOM query to count # results on the page.

But say for the case of when we want to populate an analytics call with information from both DirectAnswers and UniversalResults. Is this something the library would support?

Q2: Any change to the results through search functionality, please. We just need a way to differentiate that initial search on load and subsequent user-action searches.

**Comment by oshi97** [comment]
🔥🔥🔥

**Comment by oshi97** [comment]
Closed with #579
