### ISSUE TITLE
Uncaught ReferenceError: google is not defined

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#508]
On dist-v.0.12.1

When navigating on universal results to a search with a map component, getting error
"Uncaught ReferenceError: google is not defined" causing the maps to not load

This is pointing to references of the global variable "google" in
src/ui/components/map/providers/googlemapprovider.js

When setting the timeout to a bigger number (1000)
src/ui/components/map/providers/googlemapprovider.js#100
the maps load correctly again

**Comment by alexisgrow** [comment]
Thanks @creotutar! I'm investigating this, I'll post here when I have an update.

**Comment by alexisgrow** [comment]
Code has been pushed to fix this issue. We're cutting release v0.12.2 right now.
