### ISSUE TITLE
facets searchOnChange Causing Console Errors (and Impacting SpellCheck)

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#509]
**Current behavior:** When I set "searchOnChange" in the facets component to true, get a bunch of console errors. (In addition, the spell check component does not show up, but I'm guessing it has to do with some issues in setting state). When I remove the "searchOnChange" attribute, no console errors, and spellcheck works fine. 

**Expected behavior:** Setting the search on change attribute should work fine (and the spell check component should show up)

**Version:**
Verified this on dev/v0.13.0 (disregard the fact that I'm using the styling and templates) -- can work to verify on an earlier version (I'm guessing it's always been there since we didn't change anything having to do with facets in this version).

**Console Error:**

![image](https://user-images.githubusercontent.com/22160788/75183631-eae21600-5710-11ea-92a5-0d4ee5c89978.png)

`<!doctype html>
<html>

<head>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700&display=swap" rel="stylesheet">

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5">
    <meta name="format-detection" content="telephone=no">
    <script src='./sharedconfig.js'></script>
    <script src='./combiner.js'></script>
    <script src='./builderHelpers.js'></script>
    
    <script src="./templates.js"></script>

    <link rel="stylesheet" href="../css/all.css">
    <link rel="stylesheet" type="text/css" href="https://assets.sitescdn.net/answers/dev/vr/filters2/answers.css">

    <link rel="stylesheet" href="../css/healthcare.css">
    <style>
        ul, li {
            list-style: none;
            padding: 0;
            margin: 0;
        }
        .yxt-StandardCard-image {
            min-width: 25%;
        }

        .yxt-Results-titleBar { 
            display: none !important; 
        }

    </style>

    
    <title>Healthcare Demo</title>
    <script>
        function initAnswers() {
            const verticalKey = "providers";
            ANSWERS.init({
                apiKey: sharedConfig.apiKey,
                experienceKey: sharedConfig.experienceKey,
                debug: true,
                businessId: sharedConfig.businessId,
                templateUrl: "https://assets.sitescdn.net/answers/dev/vr/filters2/answerstemplates.compiled.min.js",
                locale: 'en',
                experienceVersion: sharedConfig.experienceVersion,
                promptForLocation: true,
                fieldFormatters: buildFieldFormatters(sharedConfig),
                search: {
                  defaultInitialSearch: '',
                  verticalKey,
                },
                navigation: {
                    tabs: buildTabLinks(sharedConfig, verticalKey)
                },
                onReady: function () {

                    this.addComponent('SearchBar', {
                        container: '#search-form',
                        query: '',
                        verticalKey,
                        allowEmptySearch: true,
                        ...sharedConfig.componentSettings.SearchBar,
                    });  

                    this.addComponent('VerticalResults', {
                        container: '#results',
                        ...sharedConfig.verticals.providers,
                        verticalKey: 'providers'               
                    });

                    this.addComponent('LocationBias', {
                        container: '.location-bias-container',
                        ...sharedConfig.componentSettings.LocationBias

                    })

                    this.addComponent('Facets', {
                        container: '.facets',
                        searchOnChange: true,
                        verticalKey,
                        showMoreLimit: 5,  
                        expand: false                      
                    });  

                    this.addComponent('SortOptions', {
                        container: '.sorting',
                        ...sharedConfig.verticals.providers.componentSettings.Sorting

                    });

                    // TODO (Rose): Styling for pagination needs work, leaving out for right now
                    this.addComponent('Pagination', {
                        container: '.pagination'
                    });                   

                    this.addComponent('SpellCheck', {
                        container: "#spell-check",
                        ...sharedConfig.componentSettings.SpellCheck
                    });

                }
            });
        }
    </script>
    <script src="https://assets.sitescdn.net/answers/dev/v0.13.0/answers.min.js" onload="initAnswers()" async
        defer></script>
</head>

<body>
    <div style="background-color: #1f295a;">
        <div class="container" style="max-width: 1200px; margin: 0 auto;">
            <div style="display: flex; padding: 14px; justify-content: space-between;">
                <div style="font-size: 30px; font-weight: normal; font-family: system-ui; color: white">Providers</div>
            </div>
        </div>
    </div>
    <div class="Answers">
        <div class="Answers-navWrapper">
            <div class="Answers-container" style="width: 1000px;">
                <div class="Answers-search js-answersSearch" id='search-form'></div>

            </div>
        </div>

        <div class="Answers-Big-Wrapper" style="display: flex; max-width: 1100px; margin: 0 auto;">
            <div class="sticky">
                <div class="filter-search-container"></div>
                <div class="facets"></div>
                <div class="sorting"></div>
            </div>
            <div class="Answers-container Answers-resultsWrapper">
                <div class="Answers-spellCheck js-answersSpellCheck" id='spell-check'></div>
                <div class="Answers-verticalResults" id='results'></div>
                <div class="Answers-qaSubmission js-Answers-qaSubmission"></div>
                <div class="location-bias-container"></div>
                <div class="pagination"></div>
            </div>
        </div>
    </div>
</body>

</html>`

**Comment by alexisgrow** [comment]
This has been fixed in v1.1.1, closing!
