### ISSUE TITLE
Expose "Distance" in TemplateMappings

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#529]
In the the VerticalResults and UniversalResults component, allow users to access the "distance" attribute in their TemplateMappings.

In other words, I should be able to do this:

```
card: {
  cardType: "Standard",
  templateMappings: (item) => {
    console.log(item);
    return {
      title: item._raw.name,
      subtitle: `Department: ${item._raw.name} `,
      details: item._raw.distance,  //here's where I use distance
      image: item._raw.headshot ? item._raw.headshot.url : null,
      url: '#',
      showMoreText: "show more",
      showLessText: "put it back"
    }
  }
```
see `response.results.distance` here: https://liveapi.yext.com/v2/accounts/me/answers/vertical/query?v=20190101&api_key=01db1d1e5ebbaa7ea2e6807ad2196ab3&input=offices&answersKey=yextanswersconfig&verticalKey=offices&locale=en

Note that @aginsberg did (or attempted to do) this for the providence fork here, https://github.com/yext/answers/commit/9538c81ddae2dd09185d1cb182caf96b0824ab44

**Comment by rosiegrant** [comment]
tentatively scheduled for 0.13.1. note this is not changing the template, just exposing the attribute. @tmeyer2115 to make an item

**Comment by rosiegrant** [comment]
Phase 1:
1. Expose distance in the mappings. Prefix with `d_` for derived field in mapping, so admin would reference as `d_distance`
2. Conversion function, admin will need to pass imperial vs. metric. IE p => ${convertDistance(p.d_distance, "metric")}

(would need to add logic to do singular vs. plural).

Phase 2:
Add a setting to the init for `metricSystem` (imperial vs. metric). Whichever one you pick should impact how the SDK formats distance. If not set, it should default based on the locale set in the init.

**Comment by oshi97** [comment]
Hi @rosiegrant, would it be better to just have distance be the second argument of the dataMappings function you can pass in? The d_ business seems cool but also a little unintuitive.

**Comment by oshi97** [comment]
so instead of: 
```
dataMappings = (item) => { ... }
```
instead being:
```
dataMappings = (item, distance) => { ... } 
```
The second argument could be omitted if it was unused, so you wouldn't have to specify distance if you didn't need it.

**Comment by oshi97** [comment]
After looking into this a bit more, it would probably be even better to just expose it as part of the "item" as "item.distance, since that's also how the data is organized in the response. So you could do something like
```
dataMappings = item => {
    const distance = item.distance;
    console.log("I am the distance!', distance)
}
```

**Comment by oshi97** [comment]
Proposed PR: https://github.com/yext/answers/pull/581

**Comment by oshi97** [comment]
It's in 13.2!
