### ISSUE TITLE
400 Response in Q&A Endpoint Should Display Error

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#570]
**Current Behavior:** When the q&a endpoint returns an error (400), we still display a successful response on the front end.

**Expected Behavior:** If an error is returned from the API, we should display our error state (which already exists here, https://github.com/yext/answers/blob/8af0620afc6a8fab42b0e113414c73fe546e3b60/src/ui/templates/questions/questionsubmission.hbs#L44)

**To Replicate:** 
- In your test account, add an incorrect `entityId` to the QASubmission config
- Submit a question using the frontend component
- You'll see a "thanks for your question", despite the fact that the request 400's and no question was submitted. 

<img width="779" alt="Screen Shot 2020-03-16 at 6 49 46 PM" src="https://user-images.githubusercontent.com/22160788/76806118-f7f5a080-67b6-11ea-8c10-a021cd428d26.png">

**Comment by cea2aj** [comment]
Solved by https://github.com/yext/answers-search-ui/pull/1505
