### ISSUE TITLE
Flex wrap in results causing line break between ordinals and result titles

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#575]
See https://yext.slack.com/archives/GNXRW73QA/p1584562158002100

![Pizza Ranch mobile](https://user-images.githubusercontent.com/22160788/77017702-800fad80-6951-11ea-88bf-732bce21135b.jpg)

This line of scss https://github.com/yext/answers/blob/083133b17471b4bbbed76139799e82601d999be1/src/ui/sass/modules/_Result.scss#L109 is causing the wrapping to happen on mobile here, http://answers-pizzaranch.com.yext-cdn.com.yextpages.net/?query=Locations+near+me. 

Do we need this, and if not can we remove?

**Comment by oshi97** [comment]
Hi @rosiegrant, is this still an issue with v0.13.0 of the sdk?

**Comment by oshi97** [comment]
Result.scss is dead post v13.1 of the sdk
