### ISSUE TITLE
verticalURL Lost

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#64]
I'm displaying a "view all" link in one of my templates based on a verticalURL in the universal search, it appears it's stopped appearing, which would indicate the template is no longer seeing verticalURL

`{{#if verticalURL}}<a class="view-more-link" href="{{verticalURL}}">View All <i class="fal fa-chevron-right"></i></a>{{/if}}`

**Comment by b1lly** [comment]
Should be fixed.
