### ISSUE TITLE
All SASS Variables Should be Marked with !default

### ISSUE THREAD

**Issue by benmcginnis** [yext/answers-search-ui#652]
Several SASS variables are not marked with the `!default` directive, which can cause Answers settings to override the settings of implementers' SASS files when imported via NPM.

For example: https://github.com/yext/answers/blob/15346e4f5a936da241038fbca44bd1748c995739/src/ui/sass/_layout.scss#L18

Is causing a visual bug on [covid19.nj.gov](https://covid19.nj.gov):
<img width="1172" alt="Screen Shot 2020-04-03 at 2 36 24 PM" src="https://user-images.githubusercontent.com/1206953/78393828-8e4c0380-75b8-11ea-92e4-b63eb97e25db.png">

The NJ Covid Site also uses the variable name `$container-desktop-base` but the Answers name is taking precedence.  Sass allows libraries like Answers to define their variables as defaults so that they can be overridden by implementers incorporating their sass files.

**Comment by rosiegrant** [comment]
@alexisgrow this is done right?

**Comment by alexisgrow** [comment]
@rosiegrant Yes! This was done in this commit: https://github.com/yext/answers/commit/a5af57c588057a74994b32331af18ad8c70f24b7
