### ISSUE TITLE
v0.13.1 event polyfill

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#658]
While upgrading a site to v0.13.1, noticing that when I try to click on an autocomplete suggestion in IE11, I get a console error and the suggestion is not searched.

Environment
`dist-v0.13.1`
importing `answers/dist/answers-umd.js`

Error
`SCRIPT445: Object doesn't support this action`
for line
`return new Event(event, assign$2({`

This is only the case when I implement my own CustomEvent/Event polyfills (Consulting general polyfills). I was under the impression the library was not going to be affected by user polyfills. Is this not the case?

**Comment by rosiegrant** [comment]
i pinged @bryanreed re: looking into this this week

**Comment by oshi97** [comment]
hi @creotutar ! Do you have any examples of the polyfills you wrote? @alexisgrow and I talked about it, and think it's possible we can change line 177 of src/ui/dom.js to be CustomEvent instead of Event. If that doesn't work, I think we could just always use our scoped polyfill, and remove lines 176 to 181.

**Comment by oshi97** [comment]
(for context lines 176 to 181 try to use CustomEvent/Event from the window if they exist)

**Comment by oshi97** [comment]
https://github.com/yext/answers/commit/1b2ae0c358494971f8ea8830bd740fc3c0256aa7#diff-130212189d8a9dfbfa0ef862f5d12e1dR177

**Comment by creotutar** [comment]
Sent you a snippet of our CustomEvent polyfill!

**Comment by oshi97** [comment]
PR out! https://github.com/yext/answers/pull/668

**Comment by oshi97** [comment]
Merged into v0.13.3!
