### ISSUE TITLE
yxt-Results-placeholders adding extra margin to page

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#664]
Hello, on v0.13.1, using dist/answers-umd.js

Noticing that the `yxt-Results-placeholder` has margin styling even though it does not show any content. This should not be the case as you can have inconsistent spacing on the universal results for instance, between verticals.

![image](https://user-images.githubusercontent.com/32468132/78791883-6ecd2600-797e-11ea-8dfb-639d8314395e.png)

Also noticing the placeholder has content in it, despite having `visibility: hidden`. Would recommend we remove the content, could have unintended effects.

**Comment by alexisgrow** [comment]
This has been fixed in v1.0.0, closing!
