### ISSUE TITLE
Geolocation does not work in ie11

### ISSUE THREAD

**Issue by oshi97** [yext/answers-search-ui#684]
Steps to recreate
open ie11 in browserstack
try to use geolocation filter's near me button
OR
open console and run below line
`navigator.geolocation.getCurrentPosition(function(p){console.log(p)}, function(e){console.error(e)})`

**Comment by nbramblett** [comment]
This should be supported since IE 9 (https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition). Are you sure it isn't an issue with browserstack's location permissions?
