### ISSUE TITLE
Breaking Change - Link Targets

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#693]
1. For title link targets in standard and legacy card, update so setting a target the `parent_ops` level works, since admins were relying on this functionality (here's what it looked like, https://github.com/yext/answers/blob/v0.12.0/src/ui/templates/results/resultsitem.hbs#L34). 

- https://github.com/yext/answers/blob/a641837a09380bcb0cd338258ae243f3e58d8be8/src/ui/templates/cards/legacy.hbs#L34

- https://github.com/yext/answers/blob/master/src/ui/templates/cards/standard.hbs#L38

We should first check if there's a target set at the card level, use it, if not, then check if there's a target at the parentOps level. 

2. In addition, any place we are setting a link target (title and CTAs), it should default to "_self". we are currently defaulting to "_blank" and this has caused a breaking change. Since "_self" is the default target, we can just remove these defaults and it should work. 

- https://github.com/yext/answers/blob/a641837a09380bcb0cd338258ae243f3e58d8be8/src/ui/templates/cards/legacy.hbs#L34
- https://github.com/yext/answers/blob/master/src/ui/templates/results/resultsaccordion.hbs#L38

(Places where we aren't defaulting target so we don't need to update:
- https://github.com/yext/answers/blob/master/src/ui/templates/ctas/cta.hbs#L3
- https://github.com/yext/answers/blob/master/src/ui/templates/cards/standard.hbs#L38)

**Comment by rosiegrant** [comment]
@nbramblett @bryanreed I mixed these up, I'm sorry. 

Part 1 is correct. 

Part 2:

Any place we are setting a link target (title and CTAs), **it should default to "_blank"**. in certain places, we used to default to "_blank", and by removing it, it caused a breaking change. Using _self causes it to open in the current frame, which is not 

- [ ] https://github.com/yext/answers/blob/master/src/ui/templates/results/resultsaccordion.hbs#L38 can be left as-is, since we are already defaulting to "_blank"
- [ ] https://github.com/yext/answers/blob/master/src/ui/templates/cards/legacy.hbs#L34 can be left as-is, since we are already defaulting to "_blank"
- [ ] https://github.com/yext/answers/blob/master/src/ui/templates/ctas/cta.hbs#L3 should default to _blank
- [ ] https://github.com/yext/answers/blob/master/src/ui/templates/cards/standard.hbs#L38 should default to _blank. 

Again really sorry for the mix-up.

**Comment by nbramblett** [comment]
This has been resolved by PR #694
