### ISSUE TITLE
Need Border on Accordion Filters

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#762]
Please add the following styling
```
.yxt-Results.yxt-Accordion .yxt-Results-filters {
    border-right: .0625rem solid #e9e9e9;
    border-left: .0625rem solid #e9e9e9;
}
```
I think we can accomplish this by removing line 159 - 163 here: https://github.com/yext/answers/blob/master/src/ui/sass/modules/_Results.scss#L159

**Comment by alexisgrow** [comment]
Hi Rose, this has been fixed in v1.1.1. Closing!
