### ISSUE TITLE
Pagination alignment

### ISSUE THREAD

**Issue by rosiegrant** [yext/answers-search-ui#766]
Better align the pagination buttons by default

 @alexisgrow had this suggested fix: 
```
.yxt-Pagination-chevron, .yxt-Pagination-doubleChevron {
  display: flex;
}
```
before:
![Screen Shot 2020-05-07 at 5 45 47 PM](https://user-images.githubusercontent.com/22160788/81347673-a36df380-908a-11ea-9b53-a47a70fdd272.png)

after:
![Screen Shot 2020-05-07 at 5 45 31 PM](https://user-images.githubusercontent.com/22160788/81347688-aa950180-908a-11ea-858b-b64c9ebfdd96.png)

**Comment by alexisgrow** [comment]
This has been fixed in v1.1.1, closing!
