### ISSUE TITLE
Facets checkbox misaligned if text spans 2 lines

### ISSUE THREAD

**Issue by oshi97** [yext/answers-search-ui#830]
![image](https://user-images.githubusercontent.com/23005393/83553332-0a8b9600-a4d9-11ea-841a-1f18c816770a.png)

noticed in version 1.4.0, but likely has been an issue for a longer time

**Comment by alexisgrow** [comment]
Hi Oliver! I also noticed this! This was introduced in v1.4.0 when the checkboxes were redesigned, and it has been fixed in this PR: https://github.com/yext/answers/pull/847. Going to close this now rather than wait for the release since v1.4.0 hasn't been released yet
