### ISSUE TITLE
RADIUS_FILTER 0 value documentation clarity

### ISSUE THREAD

**Issue by bhainesva** [yext/answers-search-ui#915]
Hi all, 

I struggled a little using the RADIUS_FILTER so opening this issue to get people's opinions on whether the documentation could be clarified. 

The comment for the `value` property of the RADIUS_FILTER options says
> Required, the value of the radius to apply (in meters). If this value is 0, will not filter by radius.

Not sure this is wrong but I found it misleading. It suggests to me if you're trying to create an option that removes any distance limits you should set the value to 0. But what actually happens in that case is that it falls back to the normal answers radius logic which applies a limit based on the query. To really remove radius filtering you need to specify a really large number as the value.

Thanks for consideration.

**Comment by oshi97** [comment]
Hey Ben,

This is definitely misleading, just put up a PR (https://github.com/yext/answers/pull/925) to address this. Please take a look when you get the chance!

**Comment by oshi97** [comment]
PR merged in! closing this
